### ISSUE TITLE
No Data by using Depth_Registration

### ISSUE THREAD

**Issue by brotherxiang00** [ros-drivers/openni_launch#14]
I am following instruction on http://wiki.ros.org/openni_launch, but some problems occur.

When rosrun image_view disparity_view image:=/camera/depth/disparity, it works well. But when I enable depth_registration by rosrun rqt_reconfigure rqt_reconfigure, there is image displayed. I use rostopic echo /camera/depth_registered/disparity, the output is a lot of zero on terminal.

Could you please tell me how to fix it? As I am very new to ROS, could you please give me a step by step solution? Many thanks.

**Comment by jonbinney** [comment]
Hi @brotherxiang00 - I haven't used openni_launch in a while so I'm not sure what this might be. You'll probably have better luck asking this kind of question on ROS answers: http://answers.ros.org/questions/

**Comment by brotherxiang00** [comment]
@jonbinney Thanks for your reply. I asked on ROS answers, but no reply..

**Comment by 130s** [comment]
Moved to openni_camera repo. Please follow the referenced link.
