### ISSUE TITLE
Status for Indigo?

### ISSUE THREAD

**Issue by davetcoleman** [ros-drivers/openni_launch#16]
Any progress for releasing this into indigo? I'm working on moving my robot to indigo and found this missing. Thanks!

**Comment by piyushk** [comment]
@jack-oquin and I will probably do a freenect_stack release into Indigo soon, now that libfreenect has been released. We can probably do this one at the same time.

**Comment by davetcoleman** [comment]
Thanks!

**Comment by jack-oquin** [comment]
I'll add both openni_stack and freenect_stack to the indigo/distribution.yaml, so we can run pre-release tests on them. If that works, I am willing to release the Hydro openni_stack-1.9.5 to Indigo. 

But, I am not the maintainer, and don't want to take responsibility for merging and testing other contributions.

**Comment by jack-oquin** [comment]
**UPDATE**: looks like openni_camera is also missing and needed for Indigo.

**Comment by piyushk** [comment]
@jack-oquin I agree. I was planning on releasing the last release from the hydro-devel branch to Indigo without any changes.

**Comment by jack-oquin** [comment]
I did not define openni_stack or openni_camera sources for Indigo, because their branch names are tied to specific ROS distros, and I don't want to interfere with the repository branch structures.

@jonbinney: the openni_stack groovy-devel and hydro-devel branches are currently identical. Do you want to define yet another identical branch for Indigo? I am willing to assist, if you tell me what you want to do.

**Comment by jonbinney** [comment]
I think that forking and having an indigo-devel branch still makes sense here. If you can do that, I'd be grateful.

**Comment by piyushk** [comment]
@jonbinney Sure. Could you give me the necessary permissions for openni_launch and openni_camera?

**Comment by jack-oquin** [comment]
@piyushk: I created indigo-devel copies of hydro-devel for both repositories, but left the hydro-devel branches as their defaults.

Note that openni_camera has a different maintainer, @jkammerl.

**Comment by jonbinney** [comment]
@piyushk and @jack-oquin i've added both of you to the openni team so you have commit access. Thanks a lot for helping!

**Comment by jack-oquin** [comment]
The release worked. It's in shadow-fixed now, so other packages can be released that depend on it.

**Comment by davetcoleman** [comment]
Thanks!
