### ISSUE TITLE
Allow nodelets to run under a given namespace

### ISSUE THREAD

**Issue by jonbinney** [ros-drivers/openni_launch#2]
Migrated from: https://kforge.ros.org/openni/trac/ticket/64
Patch: https://gist.github.com/4513252

openni_launch currently resolves tf frame_ids and namespaces to the top level namespace, which is problematic in multi robot systems.
This is a simple (but hackish) patch that allows users to append a given namespace to both the tf frame ids and the node/topic namespace.

I have updated the patch to be less hackish. Here are a few different command line tests to run the launch script after applying this patch. 
No change, runs as before:
roslaunch openni_launch openni.launch

Runs all names/topics/services in the namespace '/robot1'. All frame_ids will be prefixed with /robot1 (e.g. /robot1/camera_link):
ROS_NAMESPACE=/robot1 roslaunch openni_launch openni.launch ns:=/robot1 --screen
Runs all names/topics/services in the namespace '/robot1'. All frame_ids will be prefixed with /robot1_tf (e.g. /robot1/camera_link):
ROS_NAMESPACE=/robot1 roslaunch openni_launch openni.launch ns:=/robot1 tf_prefix:=/robot1_tf --screen
These changes mirror the changes applied for freenect_stack 0.1.1

**Comment by bit-pirate** [comment]
I think we can close this. The above pull request solves this issue.
