### ISSUE TITLE
Release for Jade

### ISSUE THREAD

**Issue by vrabaud** [ros-drivers/openni_launch#21]
Thx for releasing that for Jade

**Comment by 130s** [comment]
I can take care of this if I have write access to the release repository.

**Comment by vrabaud** [comment]
@130s, thx ! done

**Comment by 130s** [comment]
Waiting for https://github.com/ros-drivers/rgbd_launch/issues/17 to be closed - can't be released without rgbd_launch.

**Comment by 130s** [comment]
Done https://github.com/ros/rosdistro/pull/9837
