### ISSUE TITLE
No data received

### ISSUE THREAD

**Issue by arunavanag591** [ros-drivers/openni_launch#22]
After copying the source file to my catkin_ws and then building the package ( catkin_make ). I am able to launch using the roslaunch openni_launch openni.launch, but in rviz i can see no data. When i roslaunch the openni , it throws a bunch of errors in between. I don't know what is going on?

**Comment by UnexpectedGinger** [comment]
Im having the same issue now, but without errors. Were you able to resolve this? If so, how?

**Comment by 130s** [comment]
Moved to openni_camera repo. Please follow the referenced link.
