### ISSUE TITLE
Kinetic release

### ISSUE THREAD

**Issue by vrabaud** [ros-drivers/openni_launch#27]
Him, can you please release it for Kinetic ? Thx !

**Comment by 130s** [comment]
I can take care of this on this weekend unless either someone else can earlier or there's a way to `bloom` from Android.

**Comment by 130s** [comment]
Blocked by https://github.com/ros/rosdistro/pull/11447 for now.

**Comment by 130s** [comment]
Donezo https://github.com/ros/rosdistro/pull/11448

**Comment by vrabaud** [comment]
awesome, thx !
