### ISSUE TITLE
Consolidate rgbd repositories into a single repo

### ISSUE THREAD

**Issue by 130s** [ros-drivers/openni_launch#30]
The following repositories contain a single package. I suggest to create a new repo where we move all of these 3 packages to, in order to reduce the maintenance effort.

1. openni_launch
1. rgbd_launch
1. openni_camera

**Background**
Despite the inactive development, the release tasks for these packages still takes certain amount of work. For Lunar this time, I took charge of it and for total it took almost an hour,  mainly because these packages are inter-depended and I had to make release one by one and wait for the binary to become ready, in order for `bloom` to be able to resolve the necessary dependency.

**Suggested solution**
Create a new repo and move all of these 3 packages there.
Suggestion for the repo name appreciated. Here I temporarily use *`openni_meta`*.

New repo and the contents (being updated over time taking suggestions in):

```
ros-drivers/openni_meta
|- freenect_camera
|- freenect_launch
|- openni_camera
|- openni_launch
|- openni_meta
|- rgbd_launch
```

`openni_meta` is a meta package that run_depends on these 3 packages.

**Comment by piyushk** [comment]
I understand the issues with extra maintenance effort. If you would prefer, you can also merge `freenect_*` into a meta repo as well.

I also recommend calling the repository `rgbd_meta`.

**Comment by 130s** [comment]
@piyushk I'm only doing the release tasks for these packages so feedback from actual developers like you is appreciated.

Do you mean to include `freenect_*` into the same single repo where `openni_*` and `rgbd_*` are, and that repo name can be `rgbd_meta`?

**Comment by piyushk** [comment]
@130s Thanks for spending time releasing!

Yes, that is exactly what I meant!

**Comment by 130s** [comment]
I see.

@piyushk could you provide one more feedback? A caveat I can think of by the unified release from the aggregated repo is that all packages need to align the same package version. The current ersions taken from the main branch of each repo:

- 0.4.2 https://github.com/ros-drivers/freenect_stack (btw I was able to find only this package that prefixes with `freenect_`).
- 1.9.5 https://github.com/ros-drivers/openni_camera
- 1.9.8 https://github.com/ros-drivers/openni_launch
- 2.1.3 https://github.com/ros-drivers/rgbd_launch

I propose either:
- 2.2.0 (adjusting to the highest available, rgbd_launch, and incremented minor ver)
- 3.0.0 (similar to adjusting to the highest available but incremented major ver for simplicity)

**Comment by piyushk** [comment]
That's the only repository. There are multiple packages inside it.

I would recommend `2.1.4` across all of them, since this change maintains backward compatibility. However, given that other numbers are going to change, `2.2.0` sounds good to me.

**Comment by mintar** [comment]
What about openni2_camera and openni2_launch? openni2_launch also depends on rgbd_launch, so by that logic it should also go into that merged repo.

Personally, I'm not convinced of the proposal to merge everything together. Especially openni2_camera, openni_camera and freenect_stack don't seem to have any inter-dependencies (please correct me if I'm wrong). It might be more convenient to release everything in one go, but I think this is outweighed by the loss of clarity when trying to pinpoint a bug in one mega-repository.

Also, there are third-party packages for cameras such as the Orbbec Astra that include rgbd_launch. It's a bit weird for them to require the freenect, openni and openni2 libraries just to include some launch file.

Just my 2 cents, it's up to you maintainers to decide. :)

**Comment by skohlbr** [comment]
Note also the Intel Realsense integration (https://github.com/intel-ros/realsense) uses rgbd_launch, so forcing installation of all openni-related s/w appears undesirable.

**Comment by 130s** [comment]
Thanks for the inputs!

> It's a bit weird for them to require the freenect, openni and openni2 libraries just to include some launch file.

If the developers of downstream driver packages (say Astra's ROS pkg) want to build the upstream driver packages from source, yes they would clone unnecessary codes in addition, which I realized a bit less useful/user-friendly (or whatever appropriate way you call) indeed.
(Meanwhile, if they can use binary, then obviously they could only use the specific binary pkg they need.)

How about coupling only those that makes more sense? 
E.g. I found [freenect_stack](https://github.com/ros-drivers/freenect_stack) is a good example where driver and launch packages sit together.
```
freenect_stack
|- freenect_camera
|- freenect_launch
|- freenect_stack
```
So, new proposed layout (top level is a repository):

```
openni_camera
|- openni_camera
|- openni_launch

openni2_camera
|- openni2_camera
|- openni2_launch

rgbd_launch
```
For `openni2`, I already opened separately a PR https://github.com/ros-drivers/openni2_camera/pull/55 to merge into the existing `openni2_camera` repo.

Not sure how necessary meta packages are for these consolidation, since the dependency is only one-way from launch to driver, not the other way round, so that even those who build from source `rosdep` should be helpful to systematically install dependency.

**Comment by mintar** [comment]
So, if I understand you correctly, you're now proposing to merge openni_camera and openni_launch into one repo, openni2_camera and openni2_launch into a second repo, and keep rgbd_launch separate? That makes sense to me.

**Comment by 130s** [comment]
@mintar Yes. Only change I now suggest after all is consolidating `openni_*` packages.

@piyushk @skohlbr I appreciate your input.

**Comment by piyushk** [comment]
@130s: Your proposed solution sounds good to me, and I think conforms with the other feedback provided. :+1:

**Comment by mikaelarguedas** [comment]
Thanks @130s for the initiative!
From recent experience in shuffling code across repositories. It's hard to estimate how many people rely on the current location of the code by cloning hard-coded url in various scripts. The easiest way to move forward without breaking earlier distros is to branch out (kinetic-devel or lunar-devel) and keeping the current upstream branch in the same state (this way EOL distros like Jade can still be built from source). The new branch can be cleaned of the code and add a deprecation + redirection in the README.
It may also be valuable to announce it on discourse so that people relying on the current layout and not watching this repository can be notified before the migration.

**Comment by 130s** [comment]
@mikaelarguedas
Thanks for sharing the insight. Still trying to understand, if we strictly apply what you're suggesting, should we do this in the next distro (M) since there might be already users who're pointing to the current latest branch?

**Comment by mikaelarguedas** [comment]
@130s If we want to go all the way yeah we would wait until ROS-M. Then its a judgement call. I'm usually trying to not make any potentially breaking change in LTS distros but allow myself to try out changes that I think are beneficial on non-LTS without waiting for the next distro to be out. So in this case I'd branch out for lunar and consolidate the repos on `lunar-devel` but keep indigo and kinetic as is to make sure not to break anything. Then as I said it's up to the maintainer

**Comment by 130s** [comment]
I see. That by itself makes sense.

Then with making multiple branches for live distros, obviously we'd need to maintain branches (cherry-picking etc.) Making new releases from multiple branches also adds up more work no matter how small it is. In addition personall, primary motivation for my maintenance contribution is for Indigo as my main project is still on Indigo. With all of these, I'd suggest:

- Freeze an old repo (openni_launch). Add deprecation notice and navigate to a new consolidated repo.
- Make a new release from the new repo only.
- New commits are only merged into the new repo.

This way, existing usecases shouldn't be broken. Only (minor) caveats:
- a. those who use `openni_launch` by source won't receive any new changes unless they switch to point to the new repo
- b. there will be 2 locations where you find `openni_launch/indigo-devel` branch. 
- c. Registered location in `rosdistro` will be updated.

I think these can be mitigated by making proper announcement and adding a notification at the old repo.

**Comment by 130s** [comment]
Thank you for the discussion. Closing as I've done pretty much all moving chore:
- openni_launch is moved to openni_camera https://github.com/ros-drivers/openni_camera/pull/57
- openni_launch repo deprecation notice https://github.com/ros-drivers/openni_launch/commit/f09a42d9e5d39dadc6f578d1794dd258d1f42569
- rosdistro entry updated (ongoing at the moment) https://github.com/ros/rosdistro/pull/16710
- Move open issues and the comments there. Done by https://github.com/IQAndreas/github-issues-import (e.g. https://github.com/ros-drivers/openni_camera/issues/65)

**Comment by 130s** [comment]
I disabled the "issue" feature on this repo to avoid new issues, but apparently it will disabled access to all  existing issues regardless open or not. So I re-enabled the issue.

Also, I could import closed issues if I wanted to, but that would send many spams to the subscribers on the new repo so I refrained.
