### ISSUE TITLE
'process has died' while running openni.launch with kinect for xbox360

### ISSUE THREAD

**Issue by blueeaglex** [ros-drivers/openni_launch#31]
Hardware:1.kinect1.0 for xbox360
                 2.PC with usb2.0              
Software: Ubuntu16.04 LTS, ros-kinetic-desktop-full
I tried to excute openni.launch and get these errors:
```
started roslaunch server http://pdw-laptop:33931/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_hw/max_range: 4.0
 * /camera/disparity_registered_hw/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_base_link (tf2_ros/static_transform_publisher)
    camera_base_link1 (tf2_ros/static_transform_publisher)
    camera_base_link2 (tf2_ros/static_transform_publisher)
    camera_base_link3 (tf2_ros/static_transform_publisher)

auto-starting new master
process[master]: started with pid [9207]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8c588874-654d-11e7-ab6f-00e0b412588a
process[rosout-1]: started with pid [9220]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [9237]
process[camera/driver-3]: started with pid [9238]
process[camera/rgb_debayer-4]: started with pid [9239]
process[camera/rgb_rectify_mono-5]: started with pid [9245]
process[camera/rgb_rectify_color-6]: started with pid [9258]
process[camera/ir_rectify_ir-7]: started with pid [9267]
process[camera/depth_rectify_depth-8]: started with pid [9282]
[ INFO] [1499676940.858628822]: Initializing nodelet with 4 worker threads.
process[camera/depth_metric_rect-9]: started with pid [9297]
process[camera/depth_metric-10]: started with pid [9322]
process[camera/depth_points-11]: started with pid [9337]
process[camera/register_depth_rgb-12]: started with pid [9343]
process[camera/points_xyzrgb_sw_registered-13]: started with pid [9349]
process[camera/depth_registered_sw_metric_rect-14]: started with pid [9366]
process[camera/depth_registered_rectify_depth-15]: started with pid [9378]
process[camera/points_xyzrgb_hw_registered-16]: started with pid [9387]
process[camera/depth_registered_hw_metric_rect-17]: started with pid [9391]
process[camera/depth_registered_metric-18]: started with pid [9412]
process[camera/disparity_depth-19]: started with pid [9420]
process[camera/disparity_registered_sw-20]: started with pid [9424]
process[camera/disparity_registered_hw-21]: started with pid [9432]
process[camera_base_link-22]: started with pid [9443]
process[camera_base_link1-23]: started with pid [9445]
process[camera_base_link2-24]: started with pid [9463]
process[camera_base_link3-25]: started with pid [9471]
Warning: USB events thread - failed to set priority. This might cause loss of data...
[ INFO] [1499676943.699963616]: Number devices connected: 2
[ INFO] [1499676943.800937024]: 1. device on bus 001:17 is a SensorKinect (2ae) from PrimeSense (45e) with serial id '0'
[ INFO] [1499676943.801022556]: 2. device on bus 001:17 is a SensorV2 (2ae) from PrimeSense (45e) with serial id 'A00363920469048A'
[ INFO] [1499676943.802363361]: Searching for device with index = 1
[camera/camera_nodelet_manager-2] process has died [pid 9237, exit code -11, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-camera_nodelet_manager-2.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-camera_nodelet_manager-2*.log
[FATAL] [1499676955.288648044]: Failed to load nodelet '/camera/points_xyzrgb_hw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289234539]: Failed to load nodelet '/camera/depth_registered_metric` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289355207]: Failed to load nodelet '/camera/depth_registered_hw_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289450084]: Failed to load nodelet '/camera/depth_registered_sw_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289567134]: Failed to load nodelet '/camera/points_xyzrgb_sw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289666340]: Failed to load nodelet '/camera/disparity_depth` of type `depth_image_proc/disparity` to manager `camera_nodelet_manager'
[FATAL] [1499676955.289845471]: Failed to load nodelet '/camera/disparity_registered_sw` of type `depth_image_proc/disparity` to manager `camera_nodelet_manager'
[FATAL] [1499676955.290129104]: Failed to load nodelet '/camera/depth_rectify_depth` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1499676955.290254835]: Failed to load nodelet '/camera/ir_rectify_ir` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1499676955.290365995]: Failed to load nodelet '/camera/driver` of type `openni_camera/driver` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291081899]: Failed to load nodelet '/camera/depth_registered_rectify_depth` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291270966]: Failed to load nodelet '/camera/rgb_rectify_color` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291462331]: Failed to load nodelet '/camera/depth_points` of type `depth_image_proc/point_cloud_xyz` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291763068]: Failed to load nodelet '/camera/depth_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291935707]: Failed to load nodelet '/camera/depth_metric` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291971826]: Failed to load nodelet '/camera/disparity_registered_hw` of type `depth_image_proc/disparity` to manager `camera_nodelet_manager'
[FATAL] [1499676955.291957955]: Failed to load nodelet '/camera/register_depth_rgb` of type `depth_image_proc/register` to manager `camera_nodelet_manager'
[camera/driver-3] process has died [pid 9238, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load openni_camera/driver camera_nodelet_manager --no-bond ir:=ir rgb:=rgb depth:=depth depth_registered:=depth_registered projector:=projector __name:=driver __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-driver-3.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-driver-3*.log
[camera/depth_metric-10] process has died [pid 9322, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth/image_raw image:=depth/image __name:=depth_metric __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_metric-10.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_metric-10*.log
[camera/ir_rectify_ir-7] process has died [pid 9267, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=ir/image_raw image_rect:=ir/image_rect_ir __name:=ir_rectify_ir __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-ir_rectify_ir-7.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-ir_rectify_ir-7*.log
[camera/depth_points-11] process has died [pid 9337, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyz camera_nodelet_manager --no-bond image_rect:=depth/image_rect_raw points:=depth/points __name:=depth_points __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_points-11.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_points-11*.log
[camera/depth_registered_sw_metric_rect-14] process has died [pid 9366, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth_registered/sw_registered/image_rect_raw image:=depth_registered/sw_registered/image_rect __name:=depth_registered_sw_metric_rect __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_sw_metric_rect-14.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_sw_metric_rect-14*.log
[camera/depth_registered_rectify_depth-15] process has died [pid 9378, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=depth_registered/image_raw image_rect:=depth_registered/hw_registered/image_rect_raw __name:=depth_registered_rectify_depth __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_rectify_depth-15.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_rectify_depth-15*.log
[camera/points_xyzrgb_hw_registered-16] process has died [pid 9387, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb camera_nodelet_manager --no-bond rgb/image_rect_color:=rgb/image_rect_color rgb/camera_info:=rgb/camera_info depth_registered/image_rect:=depth_registered/hw_registered/image_rect_raw depth_registered/points:=depth_registered/points __name:=points_xyzrgb_hw_registered __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-points_xyzrgb_hw_registered-16.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-points_xyzrgb_hw_registered-16*.log
[camera/rgb_rectify_color-6] process has died [pid 9258, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=rgb/image_color image_rect:=rgb/image_rect_color __name:=rgb_rectify_color __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-rgb_rectify_color-6.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-rgb_rectify_color-6*.log
[camera/depth_rectify_depth-8] process has died [pid 9282, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=depth/image_raw image_rect:=depth/image_rect_raw __name:=depth_rectify_depth __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_rectify_depth-8.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_rectify_depth-8*.log
[camera/depth_metric_rect-9] process has died [pid 9297, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth/image_rect_raw image:=depth/image_rect __name:=depth_metric_rect __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_metric_rect-9.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_metric_rect-9*.log
[camera/register_depth_rgb-12] process has died [pid 9343, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/register camera_nodelet_manager --no-bond rgb/camera_info:=rgb/camera_info depth/camera_info:=depth/camera_info depth/image_rect:=depth/image_rect_raw depth_registered/image_rect:=depth_registered/sw_registered/image_rect_raw __name:=register_depth_rgb __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-register_depth_rgb-12.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-register_depth_rgb-12*.log
[camera/points_xyzrgb_sw_registered-13] process has died [pid 9349, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb camera_nodelet_manager --no-bond rgb/image_rect_color:=rgb/image_rect_color rgb/camera_info:=rgb/camera_info depth_registered/image_rect:=depth_registered/sw_registered/image_rect_raw depth_registered/points:=depth_registered/points __name:=points_xyzrgb_sw_registered __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-points_xyzrgb_sw_registered-13.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-points_xyzrgb_sw_registered-13*.log
[camera/depth_registered_hw_metric_rect-17] process has died [pid 9391, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth_registered/hw_registered/image_rect_raw image:=depth_registered/hw_registered/image_rect __name:=depth_registered_hw_metric_rect __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_hw_metric_rect-17.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_hw_metric_rect-17*.log
[camera/depth_registered_metric-18] process has died [pid 9412, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/convert_metric camera_nodelet_manager --no-bond image_raw:=depth_registered/image_raw image:=depth_registered/image __name:=depth_registered_metric __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_metric-18.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-depth_registered_metric-18*.log
[camera/disparity_depth-19] process has died [pid 9420, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/disparity camera_nodelet_manager --no-bond left/image_rect:=depth/image_rect_raw right:=projector left/disparity:=depth/disparity __name:=disparity_depth __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_depth-19.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_depth-19*.log
[camera/disparity_registered_sw-20] process has died [pid 9424, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/disparity camera_nodelet_manager --no-bond left/image_rect:=depth_registered/sw_registered/image_rect_raw right:=projector left/disparity:=depth_registered/disparity __name:=disparity_registered_sw __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_registered_sw-20.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_registered_sw-20*.log
[camera/disparity_registered_hw-21] process has died [pid 9432, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/disparity camera_nodelet_manager --no-bond left/image_rect:=depth_registered/hw_registered/image_rect_raw right:=projector left/disparity:=depth_registered/disparity __name:=disparity_registered_hw __log:=/home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_registered_hw-21.log].
log file: /home/pdw/.ros/log/8c588874-654d-11e7-ab6f-00e0b412588a/camera-disparity_registered_hw-21*.log`
```
 I tried the ideas of these links:
http://answers.ros.org/question/53089/ubuntu-1210-groovy-openni-usb30-working/
http://answers.ros.org/question/135266/problem-running-openni_launchlaunch-failed-to-load-nodelet-cameradriver-of-type-openni_cameradriver-could-not-find-library-corresponding-to-plugin/
http://answers.ros.org/question/54863/camera_nodelet_manager-1-process-has-died-error-with-kinect/

But it doesn't work.

Has anyone found the way to walk through this?

**Comment by 130s** [comment]
I suggest you first ask on http://answers.ros.org, where you'll get much more attention from the users who have experience with the package (there's only 11 people watching this repo now). If you could confirm if it's an issue that needs to be fixed on this package then please report back.

**Comment by blueeaglex** [comment]
@130s  Thanks. But I'm not able to sign up on  http://answers.ros.org for now. The web side seems to get something wrong. Maybe I should try the repo of openni_camera instead (opened https://github.com/ros-drivers/openni_camera/issues/54).

**Comment by 130s** [comment]
> I'm not able to sign up on http://answers.ros.org for now. The web side seems to get something wrong. 

That is more critical for you IMO. I'd like to help you. What do you see (share screenshot etc.)?

**Comment by blueeaglex** [comment]
@130s 
Thanks.

I just don't know what file is required.
![2017-07-12 08-28-22](https://user-images.githubusercontent.com/13675522/28096636-e913ea82-66dc-11e7-91c2-6e9da88e8176.png)

**Comment by fmnoori** [comment]
did you debug your issue ??  i am getting same problem with same specification.

started roslaunch server http://stop-01:43551/

SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/depth_registered_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_hw/max_range: 4.0
 * /camera/disparity_registered_hw/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/depth_camera_info_url: 
 * /camera/driver/depth_frame_id: camera_depth_opti...
 * /camera/driver/depth_registration: False
 * /camera/driver/device_id: #1
 * /camera/driver/rgb_camera_info_url: 
 * /camera/driver/rgb_frame_id: camera_rgb_optica...
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_hw_metric_rect (nodelet/nodelet)
    depth_registered_metric (nodelet/nodelet)
    depth_registered_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_hw (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)
  /
    camera_base_link (tf2_ros/static_transform_publisher)
    camera_base_link1 (tf2_ros/static_transform_publisher)
    camera_base_link2 (tf2_ros/static_transform_publisher)
    camera_base_link3 (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera/camera_nodelet_manager-1]: started with pid [14634]
process[camera/driver-2]: started with pid [14635]
process[camera/rgb_debayer-3]: started with pid [14636]
process[camera/rgb_rectify_mono-4]: started with pid [14649]
process[camera/rgb_rectify_color-5]: started with pid [14658]
process[camera/ir_rectify_ir-6]: started with pid [14672]
process[camera/depth_rectify_depth-7]: started with pid [14683]
process[camera/depth_metric_rect-8]: started with pid [14689]
process[camera/depth_metric-9]: started with pid [14706]
process[camera/depth_points-10]: started with pid [14724]
process[camera/register_depth_rgb-11]: started with pid [14733]
process[camera/points_xyzrgb_sw_registered-12]: started with pid [14747]
process[camera/depth_registered_sw_metric_rect-13]: started with pid [14755]
[ INFO] [1500052586.931062224]: Initializing nodelet with 4 worker threads.
process[camera/depth_registered_rectify_depth-14]: started with pid [14774]
process[camera/points_xyzrgb_hw_registered-15]: started with pid [14786]
process[camera/depth_registered_hw_metric_rect-16]: started with pid [14796]
process[camera/depth_registered_metric-17]: started with pid [14800]
process[camera/disparity_depth-18]: started with pid [14805]
process[camera/disparity_registered_sw-19]: started with pid [14816]
process[camera/disparity_registered_hw-20]: started with pid [14835]
process[camera_base_link-21]: started with pid [14850]
process[camera_base_link1-22]: started with pid [14857]
process[camera_base_link2-23]: started with pid [14873]
process[camera_base_link3-24]: started with pid [14878]
[ERROR] [1500052587.267970469]: Failed to load nodelet [/camera/rgb_rectify_mono] of type [image_proc/rectify] even after refreshing the cache: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1500052587.268035002]: The error before refreshing the cache was: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[FATAL] [1500052587.268344917]: Failed to load nodelet '/camera/rgb_rectify_mono` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[ERROR] [1500052587.415688616]: Failed to load nodelet [/camera/ir_rectify_ir] of type [image_proc/rectify] even after refreshing the cache: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1500052587.415749264]: The error before refreshing the cache was: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[FATAL] [1500052587.416018759]: Failed to load nodelet '/camera/ir_rectify_ir` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[camera/rgb_rectify_mono-4] process has died [pid 14649, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=rgb/image_mono image_rect:=rgb/image_rect_mono __name:=rgb_rectify_mono __log:=/home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_rectify_mono-4.log].
log file: /home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_rectify_mono-4*.log
[ERROR] [1500052587.565410095]: Failed to load nodelet [/camera/rgb_debayer] of type [image_proc/debayer] even after refreshing the cache: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1500052587.565463092]: The error before refreshing the cache was: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[FATAL] [1500052587.565699759]: Failed to load nodelet '/camera/rgb_debayer` of type `image_proc/debayer` to manager `camera_nodelet_manager'
[camera/ir_rectify_ir-6] process has died [pid 14672, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=ir/image_raw image_rect:=ir/image_rect_ir __name:=ir_rectify_ir __log:=/home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-ir_rectify_ir-6.log].
log file: /home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-ir_rectify_ir-6*.log
[ERROR] [1500052587.713003092]: Failed to load nodelet [/camera/rgb_rectify_color] of type [image_proc/rectify] even after refreshing the cache: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1500052587.713067546]: The error before refreshing the cache was: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libimage_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[FATAL] [1500052587.713233598]: Failed to load nodelet '/camera/rgb_rectify_color` of type `image_proc/rectify` to manager `camera_nodelet_manager'
[camera/rgb_debayer-3] process has died [pid 14636, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/debayer camera_nodelet_manager --no-bond image_raw:=rgb/image_raw image_mono:=rgb/image_mono image_color:=rgb/image_color __name:=rgb_debayer __log:=/home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_debayer-3.log].
log file: /home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_debayer-3*.log
[ERROR] [1500052587.857666409]: Failed to load nodelet [/camera/depth_metric_rect] of type [depth_image_proc/convert_metric] even after refreshing the cache: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libdepth_image_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[ERROR] [1500052587.857718832]: The error before refreshing the cache was: Failed to load library /home/ap4isr/kinetic_workspc/devel/lib//libdepth_image_proc.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory)
[FATAL] [1500052587.858070640]: Failed to load nodelet '/camera/depth_metric_rect` of type `depth_image_proc/convert_metric` to manager `camera_nodelet_manager'
[camera/rgb_rectify_color-5] process has died [pid 14658, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify camera_nodelet_manager --no-bond image_mono:=rgb/image_color image_rect:=rgb/image_rect_color __name:=rgb_rectify_color __log:=/home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_rectify_color-5.log].
log file: /home/ap4isr/.ros/log/28d7e128-68b8-11e7-9672-b8819811d451/camera-rgb_rectify_color-5*.log
W

**Comment by fmnoori** [comment]
if anyone have answer please help me

**Comment by 130s** [comment]
Again, I suggest debugging questions like this in general to be first asked on http://answers.ros.org/. 

@fmnoori please go through [support etiquette](http://wiki.ros.org/Support#Etiquette) in addition; no need for [a post like this](https://github.com/ros-drivers/openni_launch/issues/31#issuecomment-315417221) that does nothing other than begging :)

**Comment by blueeaglex** [comment]
@130s  ??? I don't know what you're talking about.
fmnoori is not me.
