### ISSUE TITLE
quick start broken with Kinect on http://www.ros.org/wiki/openni_launch

### ISSUE THREAD

**Issue by vrabaud** [ros-drivers/openni_launch#6]
The quick start on http://www.ros.org/wiki/openni_launch does not work anymore with my Kinect. Nothing is being published to /camera/depth_registered/points. /camera/depth_registered/camera_info gets stuff though.
@bit-pirate , it seems to be due to your first commit after 1.9.0

**Comment by bit-pirate** [comment]
Could you be more specific about what is not working?
I tested the quick start instructions and when using the defaults, I get both `/camera/depth/points` and `/camera/depth_registered/points`.

However, I noticed that when turning on the hardware depth registration, I don't get the unregistered nor the registered point cloud. I just filed an issue for this: https://github.com/ros-drivers/openni_launch/issues/7

**Comment by vrabaud** [comment]
Right, the behavior is different from the quick start: you first get both /camera/depth/points and /camera/depth_registered/points (before, you only had the first one), and when turning the registration you get nothing.
You should first get /camera/depth/points only, and then /camera/depth_registered/points only after turning registration on.

**Comment by bit-pirate** [comment]
I just checked the behaviour in Groovy.
By default you get both `/camera/depth/points` and  `/camera/depth_registered/points` and when turning on hardware registration you end up with only `/camera/depth_registered/points`.

So, expect the bug filed with issue 7, everything seems to work as expected, no?

**Comment by vrabaud** [comment]
ok, naybe it's in image_proc then, I'll have a look.

**Comment by piyushk** [comment]
@vrabaud What version of openni_launch are you using? I can't reproduce this error with v1.9.2. I tested quick start with both device registration enabled/disabled and submitted https://github.com/ros-drivers/openni_launch/pull/4

**Comment by vrabaud** [comment]
The latest from ros-shadow sorry, so 1.9.2 yes.

On Mon, Aug 12, 2013 at 6:59 PM, Piyush Khandelwal <notifications@github.com

**Comment by piyushk** [comment]
@vrabaud This is a bit odd. Can you try freenect.launch with depth_registration:=true/false. This might atleast help identify if image_proc is acting up or not. The system deb should do. I also have a updated revision of openni_launch/freenect_launch ready. I will point you to that.

**Comment by vrabaud** [comment]
freenect_launch works as expected: `/camera/depth/points` is published only when registration is set to False.

**Comment by vrabaud** [comment]
`/camera/depth_registered/points` gets published in both though. And when setting registration to True, it seems to shift a bit so I guess registration does happen. Why is that being published with registration=False ?

**Comment by piyushk** [comment]
It's legacy openni_launch behaviour. registration=False uses software registration, whereas registration=True uses factory calibrated registration settings to produce the registered pointcloud. The device itself publishes a registered depth image. 

IMO if you don't want to go through calibration yourself, the factory calibrated registration settings are pretty decent and I generally use them

Try the new merge between freenect_launch and openni_launch using the rosinstall file mentioned in https://github.com/ros-drivers/openni_launch/issues/5
As far as I can tell, the bug mentioned in this thread does not appear there. The same quick start instructions apply.

**Comment by vrabaud** [comment]
Using your rosintall and `roslaunch openni_launch openni.launch`, I get `/camera/depth/points` with registration to False and no `/camera/depth_registered/points`. When I set registration to True, I get nothing but `/camera/depth_registered/image_raw` and `/camera/depth_registered/camera_info`

**Comment by piyushk** [comment]
It was worth a shot. Thanks for testing it out. 

I am at a loss. I thought it might have to do something with the version of image_pipeline, but the image_pipeline trunk still works for me on my machine. Here's what I am running in my workspace (on top of updated packages from the main ROS repository).

```
 image_pipeline          git  hydro-devel          6ec7f84e41b9 github.com/ros-perception/image_pipeline.git
 freenect_stack          git  external_rgbd_launch 2c1089e4dc82 github.com/ros-drivers/freenect_stack.git
 openni_launch           git  external_rgbd_launch 1783959c1ac6 github.com/piyushk/openni_launch.git
 rgbd_launch             git  hydro-devel          f8fa1738a959 github.com/ros-drivers/rgbd_launch.git
```

It takes a good 5 seconds on my machine after I issue `rostopic echo /camera/depth_registered/points` that I actually get the point cloud. The lag is similar in rviz. I only have a 1 second lag for `rostopic echo /camera/depth/points`

I am hoping someone else can reproduce this.

**Comment by bit-pirate** [comment]
@piyushk 's PR #8 fixes multiple issues including this one. Once this PR has been merged and released, we would only need to update the quick start guide to reflect the fact that by default the RGBD point cloud is already being published from the software registration node. Furthermore we should add that enabling hardware registration is recommended, since it significantly lowers the cpu usage (~6% on my quite powerful machine).

**Comment by vrabaud** [comment]
I can confirm 1.9.4 made the quick guide work again. Thx for your big work guys ! Those packages indeed needed cleanup :)
